### PR TITLE
ignore collection count

### PR DESCRIPTION
**Pull request by sebasijan**

### CODE REVIEW

**Comment by GregFinzer** [comment]
Thanks for the pull request submission.  This implementation is going to confuse people later.  If the counts are different and one list is longer than the other then the longer list items will not be compared.  Please make a IReadOnlyCollectionComparer and ignore the count when CompareReadOnly == false

**Comment by GregFinzer** [comment]
I am thinking that maybe the IReadOnlyCollection would not be compared at all if CompareReadOnly == false

**Comment by sebasijan** [comment]
I just realised that your last comment suggests ignoring the entire collection, but I am hoping to have the functionality of just ignoring the `Count` property specific, do you have any suggestions for doing that?

**Comment by GregFinzer** [comment]
Now this is just a defect that is specific to a read only collection.  

What I would do is simply this:
1.  Set IgnoreCollectionOrder = true
2. Just not use the count property in your output:

var differencesWithoutCount = Differences.Where(o => o.ChildPropertyName != "Count" && !o.Object1TypeName.Contains("ReadOnlyCollection"));
string result = differencesWithoutCount.Aggregate(string.Empty, (current, difference) => current + (difference + Environment.NewLine));

**Comment by sebasijan** [comment]
Ye that is my current approach, but I'm not  a huge fan because I then need to specify the same for every type of collection I might be using in my classes

I just thought that it made sense to exclude `Count` when setting `CompareReadOnly = false`, since `Count` is in fact a readonly property

I can always just add the filter for any collection type I happen to be using

**Comment by sebasijan** [comment]
Updated the PR to simply ignore REadOnlyCollections when `CompareReadOnly = true`

**Comment by GregFinzer** [comment]
Deployed:  https://www.nuget.org/packages/CompareNETObjects/4.77.0

**Pull request merged**
