### PR TITLE
Added new types: DateOnly & TimeOnly

### PR DESCRIPTION
**Pull request by Kebechet**
Types DateOnly & TimeOnly are available since .NET6

Here is hopefully a correct implementation.

Resolves: https://github.com/GregFinzer/Compare-Net-Objects/issues/261

### CODE REVIEW

**Comment by GregFinzer** [comment]
@Kebechet The solution build failed.

**Comment by GregFinzer** [comment]
@Kebechet Any updates?

**Comment by Kebechet** [comment]
@GregFinzer nope, I have it noted and when I will have some free time I will look into that

**Comment by GregFinzer** [comment]
@Kebechet Ping.  😄

**Comment by GregFinzer** [comment]
I manually recreated the logic and merged in on this PR:  https://github.com/GregFinzer/Compare-Net-Objects/pull/290

**Comment by GregFinzer** [comment]
Deployed in version 4.80
https://www.nuget.org/packages/CompareNETObjects/4.80.0

**Pull request closed without merging**
