### PR TITLE
Allow configuring type comparers to ignore

### PR DESCRIPTION
**Pull request by mattbrailsford**
Resolves issue #306 by allowing configuration to remove type comparers

### CODE REVIEW

**Review by GregFinzer — CHANGES_REQUESTED** [review]
Please fix failing unit tests:
https://ci.appveyor.com/project/GregFinzer/compare-net-objects

**Comment by mattbrailsford** [comment]
I'm on it 👍

**Comment by mattbrailsford** [comment]
Ok, well, I'm going to have to call this a day.

I can't for the life of me get this project to compile locally so I'm just guessing at fixes. Really, I just needed to set `InternalsVisibleTo` on the `Compare-NET-Objects` to allow the `RootComparer.TypeComparers` collection to be manipulated in the unit test, but because the assembly is strongly named, I've no idea how you get that to work.

I ended up having to resort to using reflection in the unit test, which should work fine, but the build is still failing (even though all the unit tests in AppVeyor say they are passing).

Hopefully you can resolve the last build issue. Sorry I couldn't finish it off.

**Comment by GregFinzer** [comment]
Sorry.  I simply don't have time.  I will leave this here for a couple months until you can get back to it.

**Comment by mattbrailsford** [comment]
@GregFinzer no problem. If I can find the time myself, I'll come back and try and finish it off. I don't like leaving it in an unfinished state.

**Comment by pvanbuijtene** [comment]
Maybe there's an easier solution, only include the `FontComparer` for the right targets 🤔
Think it can be excluded for all non core targets, but not 100% sure yet.
https://github.com/GregFinzer/Compare-Net-Objects/blob/master/Compare-NET-Objects/RootComparerFactory.cs#L54

**Comment by GregFinzer** [comment]
@mattbrailsford Do we still need this other PR?

**Comment by jakenuts** [comment]
This is worth getting through, it's a bit offputting to have to add Drawing to a project that has no intention of drawing anything.

**Comment by mattbrailsford** [comment]
We don’t need this PR if we are just going to omit the drawing dependency 👍🏻

**Pull request closed without merging**
