### PR TITLE
Add Ignore Properties based in FieldAttributes

### PR DESCRIPTION
**Pull request by bobosss**
Ignore property by field attribute 
ex
[NotLoggable]

### CODE REVIEW

**Comment by GregFinzer** [comment]
@bobosss It already has this functionality.  See AttributesToIgnore

**Comment by bobosss** [comment]
_AttrubutesToIgnore_ 
Check if the **class** should be exluded by Attribute

My solution exludes class **properties** by attributes and also supports not operator

**Comment by GregFinzer** [comment]
The current version already excludes class, properties or fields:

AttrubutesToIgnore
A list of attributes to ignore a class, property or field

https://github.com/GregFinzer/Compare-Net-Objects/blob/master/Compare-NET-Objects/ComparisonConfig.cs

**Comment by GregFinzer** [comment]
I have updated the documentation since this was not called out:
https://github.com/GregFinzer/Compare-Net-Objects/wiki/Ignoring-Members

**Pull request closed without merging**
